CREATE TABLE IF NOT EXISTS flat (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
flat_level TINYINT(2) NOT NULL,
flat_area DOUBLE NOT NULL,
flat_number INT NOT NULL,
id_building INT NOT NULL,
INDEX flat2building_idx (id_building ASC) VISIBLE,
CONSTRAINT flat2building
FOREIGN KEY (id_building)
REFERENCES hw8.building(id)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;