CREATE TABLE IF NOT EXISTS members (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
first_name VARCHAR(45) NOT NULL,
last_name VARCHAR(45) NOT NULL,
allow2drive ENUM('1','0') NULL DEFAULT '0',
mail VARCHAR(45) NOT NULL,
ownership ENUM('1','0') NULL DEFAULT '1',
id_flat INT NOT NULL,
INDEX member2flat_idx (id_flat ASC) VISIBLE,
CONSTRAINT member2flat
FOREIGN KEY (id_flat)
REFERENCES hw8.flat (id)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;